openapi: 3.0.2
swagger: 2.0

info:
  title: 'WAES Technical Assignment'
  description: WAES Technical Assignment, handled on July 8 2019.
  version: 1.0.0
  contact:
    email: ppedemonte@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: /v1

tags:
- name: Comparisons
  description: API allowing users to create, update, and evaluate comparisons based on Base64 encoded binary data.

paths:
  /diff/{id}/left:
    put:
      tags:
      - Comparisons
      security:
      - bearerAuth: []
      summary: Upsert the left hand side of a comparison. That's is, insert if not existing, update if existing.
      parameters:
        - in: path
          name: id
          required: true
          description: Comparison Id
          schema:
            type: string
      requestBody:
        required: true
        description: Base64 encoded data for the left hand side of the given comparison.
        content:
          plain/text:
            type: string
            format: byte
      responses:
        201:
          description: Comparison side created
          headers:
            Location:
              schema:
                type: string
              description: URL of posted chirp
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpsertResponse'
        200:
          description: Comparison side updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpsertResponse'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /diff/{id}/right:
    put:
      tags:
      - Comparisons
      security:
      - bearerAuth: []
      summary: Upsert the right hand side of a comparison. That's is, insert if not existing, update if existing.
      parameters:
        - in: path
          name: id
          required: true
          description: Comparison Id
          schema:
            type: string
      requestBody:
        required: true
        description: Base64 encoded data for the right hand side of the given comparison.
        content:
          plain/text:
            type: string
            format: byte
      responses:
        201:
          description: Comparison side created
          headers:
            Location:
              schema:
                type: string
              description: URL of posted chirp
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpsertResponse'
        200:
          description: Comparison side updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpsertResponse'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /diff/{id}:
    get:
      tags:
      - Comparisons
      security:
      - bearerAuth: []
      summary: Compute and/or get comparison results for comparison with the given id
      parameters:
        - in: path
          name: id
          required: true
          description: Comparison Id
          schema:
            type: string
      responses:
        200:
          description: Comparison successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComparisonResult'
        404:
          description: Comparison not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
      - Comparisons
      security:
      - bearerAuth: []
      summary: Delete the comparison with the given id.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Comparison Id
      responses:
        204:
          description: Comparison deleted
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Comparison not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /diff/{id}/status:
    get:
      tags:
      - Comparisons
      security:
      - bearerAuth: []
      summary: Get status information for the comparison with the given id
      parameters:
        - in: path
          name: id
          required: true
          description: Comparison Id
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComparisonStatus'
        404:
          description: Comparison not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UpsertResponse:
      type: object
      required:
        - userId
        - cmpId
        - side
      properties:
        userId:
          type: string
          pattern: '^[0-9a-f\\-]{36}$'
          description: user Id
        cmpId:
          type: string
          description: comparison Id
        side:
          type: string
          enum:
            - 'left'
            - 'right'
          description: side upserted

    ComparisonResult:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - 'EQUAL'
            - 'DIFFERENT_LENGTH'
            - 'EQUAL_LENGTH'
          description: comparison status
        differences:
          type: array
          items:
            $ref: '#/components/schemas/Span'
          description: list of difference spans, only present if status is `EQUAL_LENGTH`.

    Span:
      type: object
      required:
        - offset
        - length
      properties:
        offset:
          type: integer
          minimum: 0
          description: difference span offset
        length:
          type: integer
          minimum: 1
          description: difference span length

    ComparisonStatus:
      type: object
      required:
        - userId
        - cmpId
        - version
        - lhsReady
        - rhsReady
      properties:
        userId:
          type: string
          pattern: '^[0-9a-f\\-]{36}$'
          description: user Id
        cmpId:
          type: string
          description: comparison Id
        version:
          type: integer
          minimum: 1
          description: version number, incremented whenever comparison is updated
        lhsReady:
          type: boolean
          description: whether left hand side of comparison is set
        rhsReady:
          type: boolean
          description: whether right hand side of comparison is set
        result:
          $ref: '#/components/schemas/ComparisonResult'
          description: comparison result, only if available

    Error:
      type: object
      required:
      - error
      properties:
        error:
          type: string
          description: error message
